$n$ 次元格子 $L \subseteq \mathbb{R}^m$ の順序付き基底 $\{ \mathbb{b_1} \dots \mathbb{b_n}  \}$ を
$n \times m$ 行列として受け取り、それに対してGram-Schmidtアルゴリズムを実行し、入力基底のGSOベクトルとGSO係数を出力するアルゴリズム

In [11]:
import numpy as np

def input_basis_form():
  print("Enter the dimension of the lattice.")
  print("Enter each basis vector of the lattice")
  n = int(input())
  B = np.array([list(map(int,input().split())) for _ in range(n)])
  return B

# 基底行列を入力するとそれらのGSOベクトルからなる行列とGSO係数からなる行列を出力するアルゴリズム
# サブルーチン用
def GSO_sub(B):
  # Bの行数（基底ベクトルの本数）をnとする
  n = len(B)
  # Bと同じサイズのゼロ行列(浮動小数点数成分)を生成
  # ここにGSOの結果を入れていく予定
  B_star = np.zeros_like(B, dtype=float)
  # GSO係数行列のベースを作成
  mu = np.eye(2, dtype=float)

  for i in range(n):
    B_star[i] = B[i]
    for j in range(i):
      mu[i,j] = np.dot(B[i], B_star[j]) / np.dot(B_star[j], B_star[j])
      B_star[i] -= mu[i,j] * B_star[j]
  # B_star(GSOベクトル行列)とmu(GSO係数行列)を出力
  return B_star, mu

# 基底行列を入力するとそれらのGSOベクトルからなる行列とGSO係数からなる行列を出力するアルゴリズム
# メイン処理用
def GSO():
  B = input_basis_form()
  return GSO_sub(B)

動作テスト

In [6]:
input_basis_form()

Enter the dimension of the lattice
Enter each basis vector of the lattice


array([[1, 2],
       [3, 4]])

In [9]:
B = np.array([[1, 2, 3], [4, 5, 6]])
GSO_sub(B)

(array([[ 1.        ,  2.        ,  3.        ],
        [ 1.71428571,  0.42857143, -0.85714286]]),
 array([[1.        , 0.        ],
        [2.28571429, 1.        ]]))

In [12]:
GSO()

Enter the dimension of the lattice.
Enter each basis vector of the lattice


(array([[ 1. ,  2. ],
        [ 0.8, -0.4]]),
 array([[1. , 0. ],
        [2.2, 1. ]]))