### 目的：簡単なインプットをnumpy配列に変換できるようにすること
とはいえ、いきなりn×n扱うのはしんどいので、まずは普通の配列や数から確認してみる

In [15]:
# 入力された数字を変数に代入
n = input()
# nとnの型を出力
print(n)
print(type(n))

1
<class 'str'>


In [16]:
# 入力された数字を文字列からINT型に変換
n = int(input())
# nとnの型を出力
print(n)
print(type(n))

1
<class 'int'>


In [18]:
# 1×nのINT型のデータからなる配列を入力から生成するコード
# 入力方法は
# 3
# 1 2 3
# のようにする。こうすると
# array = [1, 2, 3]
# のようになる
n = int(input())
array = list(map(int, input().split()))
# arrayとarrayの型、arrayの最初の要素の型を出力
print(array)
print(type(array))
print(type(array[0]))

[1, 2, 3]
<class 'list'>
<class 'int'>


In [ ]:
# n×mのINT型のデータからなる配列を入力値から生成するコード
# 入力方法は
# 2 3
# 1 2 3
# 4 5 6
# のようにする。こうすると
# array = [[1, 2, 3], [4, 5, 6]]
# のようになる
size = list(map(int, input().split()))
array = [list(map(int,input().split())) for i in range(size[0])]
print(size)
print(array)

[2, 3]
[[1, 2, 3], [4, 5, 6]]


#### NumPyの利用
NumpyはPythonで数値計算を行うためのライブラリで、特に行列や多次元配列の操作が得意<br>
なぜ高速なの？->NumPyの内部ではC(とFortran)が動いているから。これにより、動的型付け言語であるPythonにおいても高速な計算が実現できる<br>
NumPyを用いるには `import numpy as np` でNumPyライブラリをインポートする必要がある<br>
これにより、 `np.メソッド名` という形でNumPyが提供するメソッドを利用できる

In [6]:
# NumPyのインポート
import numpy as np

まずは配列をNumpy配列に変換したうえで、Numpyの提供するメソッドを用いて、いろんな処理を実行してみよう

相互変換

In [7]:
array = [[1, 2, 3],[4, 5, 6], [7, 8, 9]]
print(array)
# arrayの型を確認
print(type(array))
# 配列をNumPy配列に変換
array = np.array(array)
print(array)
# もう一度arrayの型を確認
print(type(array))
# Numpy配列から普通の配列に戻す
array = array.tolist()
print(type(array))
# 今後の展開のためにNumPy配列に戻しておく
array = np.array(array)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
<class 'list'>


型・次元

In [8]:
# 配列の形状を出力
print("the shape of the array is")
print(array.shape)
# 配列の次元を出力
print("the dimention of the array is")
print(array.ndim)

the shape of the array is
(3, 3)
the dimention of the array is
2


要素や行、列を取り出す

In [9]:
# 配列の要素へのアクセス(0オリジンであることに注意)
print("(1,2) entry is")
print(array[0,1])
# 1行目を取り出す(0オリジン以下略)
print("the 1st row is")
print(array[0, :])
# 2列目を取り出す
print("the 2nd column is")
print(array[:, 1])

(1,2) entry is
2
the 1st row is
[1 2 3]
the 2nd column is
[2 5 8]


配列の演算

In [10]:
array_2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
c = 3
# 和
print("sum")
print(array + array_2)
# 差
print("difference")
print(array - array_2)
# スカラー倍
print("scalar multiplication")
print(array * c)
# ドット積(内積)
print("dot product")
print(np.dot(array, array_2))
# 積
print("matrix multiplication")
print(np.matmul(array, array_2))
# 転置
print("transposed array")
print(array.T)

sum
[[10 10 10]
 [10 10 10]
 [10 10 10]]
difference
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
scalar multiplication
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
dot product
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
matrix multiplication
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
transposed array
[[1 4 7]
 [2 5 8]
 [3 6 9]]


より高度な操作

In [11]:
# 行列式
print("the determinant of the array is")
print(np.linalg.det(array))
# ランク
print("the rank of the array is")
print(np.linalg.matrix_rank(array))
# 逆行列
arr = np.array([[1,2],[3,4]])
print("the inverse matrix of the array is")
print(np.linalg.inv(arr))

the determinant of the array is
0.0
the rank of the array is
2
the inverse matrix of the array is
[[-2.   1. ]
 [ 1.5 -0.5]]


ランダムな行列の生成

In [12]:
# 3x3のランダムな整数行列を生成（0から10未満の整数）
random_int = np.random.randint(0, 10, size=(3, 3))
print("a matrix of random integers:")
print(random_int)

# 3x3のランダムな浮動小数点数行列を生成（0から1未満）
random_float = np.random.rand(3, 3)
print("a matrix of random floating point numbers:")
print(random_float)

a matrix of random integers:
[[3 6 3]
 [9 8 9]
 [0 6 8]]
a matrix of random floating point numbers:
[[0.99594784 0.01268489 0.54651586]
 [0.48969736 0.36273384 0.44011177]
 [0.4737901  0.57474723 0.23848504]]


ランダムな整数係数フルランク行列を生成（やっつけバージョン）

In [13]:
def create_randint_fullrank_matrix():
  print("Enter the size of matrix")
  s = list(map(int, input().split()))
  row = s[0]
  col = s[1]
  while True:
    rand = np.random.randint(-100, 100, size=(row, col))
    if np.linalg.matrix_rank(rand) == row:
      return rand
    else:
      continue

In [ ]:
rand = create_randint_fullrank_matrix()
print(rand)

Enter the size of matrix
